/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.istack.internal.Nullable;
import data.Siswa;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author SERVER
 */
public class InputData extends javax.swing.JFrame {

    /**
     * Creates new form InputData
     */
    public InputData(@Nullable Siswa siswa) {
        initComponents();
        setupFrame();
        if (siswa != null) {
            setData(siswa);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldNis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldAlamat = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        fieldTtl = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbL = new javax.swing.JRadioButton();
        rbP = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cbMusik = new javax.swing.JCheckBox();
        cbBaca = new javax.swing.JCheckBox();
        cbOlahRaga = new javax.swing.JCheckBox();
        cbGame = new javax.swing.JCheckBox();
        btnTambah = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Program Input Data Siswa");

        jLabel1.setText("Nama");

        fieldNama.setToolTipText("");
        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("NIS");

        fieldNis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNisActionPerformed(evt);
            }
        });

        jLabel3.setText("Alamat");

        fieldAlamat.setColumns(20);
        fieldAlamat.setRows(5);
        jScrollPane1.setViewportView(fieldAlamat);

        jLabel4.setText("Tempat, Tanggal Lahir");

        jLabel5.setText("Jenis Kelamin");

        buttonGroupGender.add(rbL);
        rbL.setText("L");

        buttonGroupGender.add(rbP);
        rbP.setText("P");
        rbP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPActionPerformed(evt);
            }
        });

        jLabel6.setText("Hobi");

        cbMusik.setText("Bermain musik");
        cbMusik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMusikActionPerformed(evt);
            }
        });

        cbBaca.setText("Membaca buku");

        cbOlahRaga.setText("Olahraga");

        cbGame.setText("Bermain game");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fieldNama)
            .addComponent(fieldNis)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
            .addComponent(fieldTtl)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbP))
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbMusik)
                                .addGap(18, 18, 18)
                                .addComponent(cbBaca)
                                .addGap(18, 18, 18)
                                .addComponent(cbOlahRaga))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBatal)))
                        .addGap(18, 18, 18)
                        .addComponent(cbGame)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldNis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTtl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbL)
                    .addComponent(rbP))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMusik)
                    .addComponent(cbBaca)
                    .addComponent(cbOlahRaga)
                    .addComponent(cbGame))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnBatal))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldNisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNisActionPerformed

    private void rbPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPActionPerformed

    private void cbMusikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMusikActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        if (isFormValid()) {
            Siswa siswa = new Siswa(fieldNama.getText(), fieldNis.getText(), fieldAlamat.getText(), fieldTtl.getText(), getSelectedGender(), getHobies());
            DaftarSiswa.addNewSiswa(siswa);
            dispose();
            JOptionPane.showMessageDialog(this, "Berhasil menambahkan data!");
        }

    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InputData(null).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTambah;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JCheckBox cbBaca;
    private javax.swing.JCheckBox cbGame;
    private javax.swing.JCheckBox cbMusik;
    private javax.swing.JCheckBox cbOlahRaga;
    private javax.swing.JTextArea fieldAlamat;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNis;
    private javax.swing.JTextField fieldTtl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbL;
    private javax.swing.JRadioButton rbP;
    // End of variables declaration//GEN-END:variables

    private String getSelectedGender() {
        String selectedGender = "";
        if (rbL.isSelected()) {
            selectedGender = rbL.getText();
        } else if (rbP.isSelected()) {
            selectedGender = rbP.getText();
        }
        return selectedGender;
    }

    private ArrayList<String> getHobies() {
        ArrayList<String> hobbies = new ArrayList<>();
        if (cbMusik.isSelected()) {
            hobbies.add(cbMusik.getText());
        } else {
            hobbies.remove(cbMusik.getText());
        }
        if (cbBaca.isSelected()) {
            hobbies.add(cbBaca.getText());
        } else {
            hobbies.remove(cbBaca.getText());
        }
        if (cbGame.isSelected()) {
            hobbies.add(cbGame.getText());
        } else {
            hobbies.remove(cbGame.getText());
        }
        if (cbOlahRaga.isSelected()) {
            hobbies.add(cbOlahRaga.getText());
        } else {
            hobbies.remove(cbOlahRaga.getText());
        }

        return hobbies;
    }

    private String getStringFromList(ArrayList<String> hobbies) {
        String hobiesInString = "";
        for (int i = 0; i < hobbies.size(); i++) {
            if (i < hobbies.size() - 1) {
                hobiesInString = hobiesInString + hobbies.get(i) + ", ";
            } else {
                hobiesInString = hobiesInString + hobbies.get(i);
            }
        }
        return hobiesInString;
    }

    private Boolean isFormValid() {
        Boolean valid = false;
        if (fieldNama.getText().length() < 5) {
            JOptionPane.showMessageDialog(this, "Nama minimal 5 karakter!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (fieldNis.getText().length() < 8) {
                JOptionPane.showMessageDialog(this, "NIS tidak boleh kurang dari 8 karakter!", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (fieldAlamat.getText().length() < 1) {
                    JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (fieldTtl.getText().length() < 1) {
                        JOptionPane.showMessageDialog(this, "Tempat, tanggal lahir tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
                    } else {
                        if (getSelectedGender() == "") {
                            JOptionPane.showMessageDialog(this, "Jenis kelamin harus dipilih!", "Error", JOptionPane.ERROR_MESSAGE);
                        } else {
                            if (getHobies().size() == 0) {
                                JOptionPane.showMessageDialog(this, "Pilih salah satu hobi!", "Error", JOptionPane.ERROR_MESSAGE);
                            } else {
                                valid = true;
                            }
                        }
                    }
                }
            }
        }
        return valid;
    }

    private void setupFrame() {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    private void setData(Siswa siswa) {
        fieldNama.setText(siswa.getNama());
        fieldNis.setText(siswa.getNis());
        fieldAlamat.setText(siswa.getAlamat());
        fieldTtl.setText(siswa.getTtl());
        rbL.setSelected(siswa.getGender() == rbL.getText());
        rbP.setSelected(siswa.getGender() == rbP.getText());
        for (int i = 0; i < siswa.getHoby().size(); i++) {
            cbMusik.setSelected(cbMusik.getText() == siswa.getHoby().get(i));
        }
    }
}
